'''
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
nums = [0, 1]
def returnNext(n):
    n.append(n[-1] + n [-2])
    return 0
while nums[-1] < 4000000:
    returnNext(nums)
print(sum([n for n in nums if n % 2 == 0]))

#Revised solution



